name: Build .exe with PyInstaller

on:
  push:
    branches: 
      - main  # 或者你想要触发工作流的分支名
  pull_request:
    branches:
      - main  # 或者你想要触发工作流的分支名
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 根据你的项目指定Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build .exe
      run: pyinstaller --onefile main.py  

    - name: Upload .exe
      uses: actions/upload-artifact@v3
      with:
        name: OrayAutoConfig.exe
        path: dist/main.exe  # 根据你的主脚本文件名调整路径
